- name: install my server
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@01
    login_host: 172.31.45.12
  tasks:
  - name: ansible to install pymysql
    ansible.builtin.pip:
      name:
      - PyMysql
      executable: pip3.9

  - name: installing mysql server
    ansible.builtin.package: 
      name: mysql-server
      state: present

  - name: starting the mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_hosts: "{{ login_hosts }}"
    ignore_errors: true
    register: mysql_info

  - name: print the mysql info
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  - name: setup mysql root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_info.failed is true            